#!/usr/bin/env node

const express = require("express");
const bodyParser = require("body-parser");
const parse = require("@prettier/plugin-ruby/src/parse.js");

const app = express();
app.use(bodyParser.json());

app.post("/", (req, res) => {
  const { code, opts = {} } = req. body;

  try {
    res.status(201).send({ ast: parse(code, [], opts), opts });
  } catch (error) {
    res.status(422).send({ error: error.message });
  }
});

app.listen(8080, () => console.log("Listening on 8080..."));
