#!/usr/bin/env node

const express = require("express");
const prettier = require("prettier");

const app = express();
const format = (code, opts) => (
  prettier.format(code, { parser: "ruby", plugins: ["@prettier/plugin-ruby"], ...opts })
);

app.use((req, res, next) => {
  console.log(`[${new Date().toUTCString()}] ${req.method} ${req.path}`);

  res.setHeader("Access-Control-Allow-Origin", "*");
  res.setHeader("Access-Control-Allow-Methods", "OPTIONS, POST");

  next();
});

app.post("/", (req, res) => {
  const data = [];

  req.on("data", chunk => data.push(chunk));
  req.on("end", () => {
    const { code, opts = {} } = JSON.parse(data);

    try {
      res.status(201).send({ code: format(code, opts), opts });
    } catch (error) {
      res.status(422).send({ error: error.message });
    }
  });
});

app.listen(8080, () => console.log("Listening on 8080..."));
