version: "3"
services:
  api:
    build: api
    ports:
    - "8080:8080"
    depends_on:
    - python
    - ruby
  python:
    build: python
    ports:
    - "8081:8080"
  ruby:
    build: ruby
    ports:
     - "8082:8080"
