version: "3"
services:
  api:
    build: api
    ports:
    - "8080:8080"
    command:
      - "./server"
    depends_on:
    - ruby
  ruby:
    build: ruby
    ports:
     - "8082:8080"
    command:
      - "./server"
