service: prettier-remote

provider:
  name: aws
  runtime: nodejs8.10

#  include:
#    - include-me.js
#    - include-me-dir/**
#  exclude:
#    - exclude-me.js
#    - exclude-me-dir/**

functions:
  format:
    handler: handler.handle
    events:
    - http:
        path: format
        method: get
